name: CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          files: |
            compose.yaml
      -
        name: Start services
        run: docker compose up --wait --no-build
      -
        name: Install Dependencies
        run: docker compose exec -T php composer install -vvv --no-ansi --no-interaction --no-progress
      -
        name: Execute tests via PHPUnit
        run: docker compose exec -T php bin/phpunit
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
